import tkinter as tk 
from tkinter import ttk 
window = tk.Tk()
window.title('combining widgets')
window.geometry('600x600')
window.minsize(width=600,height=600)
frame1 =ttk.Frame(window)
frame1.place(relx=0,rely=0,relwidth=0.3,relheight=1)
'''trylabel = ttk.Label(frame1,text='messi',background='skyblue')
trylabel.pack(expand=True,fill='both')'''
frame2 =ttk.Frame(window)
frame2.place(relx=0.3,rely=0,relwidth=0.7,relheight=1)
'''trylabel = ttk.Label(frame2,text='messi',background='skyblue')
trylabel.pack(expand=True,fill='both')'''
# frame 1 widgets 
button1 = ttk.Button(frame1,text='button11')
button2 = ttk.Button(frame1,text='button21')
button3 = ttk.Button(frame1,text='button31')
scale1 = ttk.Scale(frame1,orient='vertical')
scale2 = ttk.Scale(frame1,orient='vertical')
check_frame = ttk.Frame(frame1)
check1 = ttk.Checkbutton(check_frame,text='check1')
check2 = ttk.Checkbutton(check_frame,text='check2')
entry1 = ttk.Entry(frame1)
# frame 2 widgets 
frame21 = ttk.Frame(frame2)
frame22 = ttk.Frame(frame2)
label11 = ttk.Label(frame21,text='label1',background='skyblue')
button11 = ttk.Button(frame21,text='button1')
label21 = ttk.Label(frame22,text='label2',background='skyblue')
button22 = ttk.Button(frame22,text='button2')
# frame1 layouts 
frame1.columnconfigure((0,1),weight=1,uniform='a')
frame1.rowconfigure((0,1,2,3,4),weight=1,uniform='a')
button1.grid(row=0,column=0,sticky='nsew')
button2.grid(row=0,column=1,sticky='nsew')
button3.grid(row=1,column=0,columnspan=2,sticky='nsew')
scale1.grid(row=2,column=0,rowspan=2,sticky='nswe',pady=5)
scale2.grid(row=2,column=1,rowspan=2,sticky='nswe',pady=5)
check_frame.grid(row=4,column=0,columnspan=2,sticky='nswe')
check1.pack(side='left',expand=True)
check2.pack(side='left',expand=True)
entry1.place(rely= 0.95,relx=0,relwidth=1)
# frame 2 layout 
frame21.pack(side='left',expand=True,fill='both',padx=10,pady=10)
frame22.pack(side='left',expand=True,fill='both',padx=10,pady=10)
label11.pack(expand=True,fill='both')
button11.pack(expand=True,fill='both',pady=10)
label21.pack(expand=True,fill='both')
button22.pack(expand=True,fill='both',pady=10)
window.mainloop()
